import type { Game, Item, GameCategory } from './types';

export const gameCategories: GameCategory[] = [
  { id: 'cat-1', name: 'Adventure' },
  { id: 'cat-2', name: 'Sci-Fi' },
  { id: 'cat-3', name: 'Simulation' },
];

export const games: Game[] = [
  {
    id: 'game-1',
    name: 'Galaxy Quest',
    logoUrl: 'https://picsum.photos/seed/g-logo1/200/200',
    bannerUrl: 'https://picsum.photos/seed/g-banner1/1200/400',
    description: 'Explore a vast fantasy world, battle mythical creatures, and uncover ancient secrets in Galaxy Quest. Your journey to become a legend starts here.',
    category: 'cat-1',
    stats: {
      players: 12500,
      likes: 9800,
    },
  },
  {
    id: 'game-2',
    name: 'Neon Blade',
    logoUrl: 'https://picsum.photos/seed/g-logo2/200/200',
    bannerUrl: 'https://picsum.photos/seed/g-banner2/1200/400',
    description: 'In the neon-drenched streets of a futuristic metropolis, carve out your destiny. Engage in high-tech warfare, corporate espionage, and digital heists.',
    category: 'cat-2',
    stats: {
      players: 25000,
      likes: 15000,
    },
  },
  {
    id: 'game-3',
    name: 'Creature Keepers',
    logoUrl: 'https://picsum.photos/seed/g-logo3/200/200',
    bannerUrl: 'https://picsum.photos/seed/g-banner3/1200/400',
    description: 'Collect, train, and trade adorable pets in the vibrant world of Creature Keepers. Build your dream pet sanctuary and compete with other trainers.',
    category: 'cat-3',
    stats: {
      players: 50000,
      likes: 42000,
    },
  },
];

export const items: Item[] = [
  {
    id: 'item-1',
    name: 'Celestial Blade',
    imageUrl: 'https://picsum.photos/seed/item1/300/300',
    gameId: 'game-1',
    category: 'Item',
    rarity: 'Legendary',
    price: 10000,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-2',
    name: 'Starshard Amulet',
    imageUrl: 'https://picsum.photos/seed/item2/300/300',
    gameId: 'game-1',
    category: 'Item',
    rarity: 'Epic',
    price: 5000,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-3',
    name: 'VIP Pass',
    imageUrl: 'https://picsum.photos/seed/item3/300/300',
    gameId: 'game-1',
    category: 'Gamepass',
    rarity: 'Rare',
    price: 800,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-4',
    name: 'Plasma Rifle',
    imageUrl: 'https://picsum.photos/seed/item4/300/300',
    gameId: 'game-2',
    category: 'Item',
    rarity: 'Epic',
    price: 7500,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-5',
    name: 'Chrono-Booster',
    imageUrl: 'https://picsum.photos/seed/item5/300/300',
    gameId: 'game-2',
    category: 'Item',
    rarity: 'Uncommon',
    price: 1200,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-6',
    name: 'Data Heist Kit',
    imageUrl: 'https://picsum.photos/seed/item6/300/300',
    gameId: 'game-2',
    category: 'Gamepass',
    rarity: 'Rare',
    price: 1500,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-7',
    name: 'Rainbow Potion',
    imageUrl: 'https://picsum.photos/seed/item7/300/300',
    gameId: 'game-3',
    category: 'Item',
    rarity: 'Common',
    price: 100,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-8',
    name: 'Mythical Egg',
    imageUrl: 'https://picsum.photos/seed/item8/300/300',
    gameId: 'game-3',
    category: 'Item',
    rarity: 'Legendary',
    price: 25000,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-9',
    name: 'Pet Multiplier',
    imageUrl: 'https://picsum.photos/seed/item9/300/300',
    gameId: 'game-3',
    category: 'Gamepass',
    rarity: 'Epic',
    price: 3000,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-10',
    name: "Galactic Explorer's Pass",
    imageUrl: 'https://picsum.photos/seed/item10/300/300',
    gameId: 'game-1',
    category: 'Gamepass',
    rarity: 'Legendary',
    price: 15000,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-11',
    name: 'Cybernetic Katana',
    imageUrl: 'https://picsum.photos/seed/item11/300/300',
    gameId: 'game-2',
    category: 'Item',
    rarity: 'Legendary',
    price: 20000,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-12',
    name: 'Golden Creature Egg',
    imageUrl: 'https://picsum.photos/seed/item12/300/300',
    gameId: 'game-3',
    category: 'Item',
    rarity: 'Rare',
    price: 5000,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-13',
    name: 'Gravity Boots',
    imageUrl: 'https://picsum.photos/seed/item13/300/300',
    gameId: 'game-1',
    category: 'Item',
    rarity: 'Uncommon',
    price: 2500,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-14',
    name: 'Holo-Disguise Kit',
    imageUrl: 'https://picsum.photos/seed/item14/300/300',
    gameId: 'game-2',
    category: 'Item',
    rarity: 'Rare',
    price: 3500,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
  {
    id: 'item-15',
    name: 'Auto-Trainer',
    imageUrl: 'https://picsum.photos/seed/item15/300/300',
    gameId: 'game-3',
    category: 'Gamepass',
    rarity: 'Uncommon',
    price: 750,
    robloxUrl: 'https://www.roblox.com/game-pass/0/placeholder',
  },
];
